Emprolijando sobre todo el repositorio para el manejo de autenticacio…
EzeCasella/parkapp-android pull request #10
Opened 2021-04-09 22:52 UTC by EzeCasella

…n e informacion del usuario. Creando usuario en la BD y exponiendo metodo para obtener usuario actual de la aplicacion.

2021-04-09 22:57 UTC, bonillasanti commented
lo miro dale

2021-04-10 01:14 UTC, santiagolorenzo requested changes

2021-04-10 01:14 UTC, santiagolorenzo commented on app/src/main/java/com/probit/parkapp/ui/map/MapsFragment.java
> +    }
Eze en esta clase me parece que no te quedaron los cambios que hiciste el otro día cuando estabamos en llamada, el merge quiere volver a lo que estaba antes,

2021-04-10 01:15 UTC, santiagolorenzo requested changes
La clase MapsFragment quedó la versión vieja

2021-04-10 17:50 UTC, santiagolorenzo approved these changes
Genial!!

2021-04-10 21:12 UTC, bonillasanti approved these changes

2021-04-10 21:13 UTC, merged